### PR TITLE
add AUR package

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by cybre** [comment]
I am not going to advertise it unless you're ready to update the package regularly and not leave it broken and outdated for several months like when Budgie 10.4 got released.

**Comment by bilelmoussaoui** [comment]
The package is up to date and I'm ready to keep it that way ;)

**Comment by cybre** [comment]
I hope you do :)

**Comment by cybre** [comment]
I made a few changes so that we don't assume people only use yaourt :)

**Comment by cybre** [comment]
gnome-screenshot is no longer a dependency so you can remove that

**Comment by bilelmoussaoui** [comment]
Done!

**Pull request merged**
